In [21]:
import numpy as np
from keras.utils import np_utils
import tensorflow as tf

# Set random seed
np.random.seed(42)

# Our data
X = np.array([[0,0],[0,1],[1,0],[1,1]]).astype('float32')
y = np.array([[0],[1],[1],[0]]).astype('float32')
print(X)
print(y)

# Initial Setup for Keras
from keras.models import Sequential
from keras.layers.core import Dense, Activation

# One-hot encoding the output
y = np_utils.to_categorical(y)
print(y)

# Building the model
xor = Sequential()

# Add required layers
# This is a layer with 8 neurons
xor.add(Dense(32, input_dim=X.shape[1]))
# tanh activation function
xor.add(Activation("tanh"))
# Output layer with only one node, no need to mention the other dimension, it is inferred
xor.add(Dense(2))
# Activation function on output
xor.add(Activation("sigmoid"))

# Specify loss as "binary_crossentropy", optimizer as "adam",
# and add the accuracy metric
xor.compile(loss="categorical_crossentropy", optimizer="adam", metrics = ["accuracy"])

# Uncomment this line to print the model architecture
xor.summary()

[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
[[0.]
 [1.]
 [1.]
 [0.]]
[[1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]]
Model: "sequential_17"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_27 (Dense)             (None, 32)                96        
_________________________________________________________________
activation_27 (Activation)   (None, 32)                0         
_________________________________________________________________
dense_28 (Dense)             (None, 2)                 66        
_________________________________________________________________
activation_28 (Activation)   (None, 2)                 0         
Total params: 162
Trainable params: 162
Non-trainable params: 0
_________________________________________________________________


In [30]:
# Fitting the model
history = xor.fit(X, y, epochs=10, verbose=0)

# Scoring the model
score = xor.evaluate(X, y)
print("\nAccuracy: ", score[-1])

# Checking the predictions
print("\nPredictions:")
print(xor.predict_proba(X))

4/4 [==============================] - 0s 106us/step

Accuracy:  0.5

Predictions:
[[9.9960881e-01 9.9999964e-01]
 [9.9999881e-01 9.9968708e-01]
 [1.2065665e-04 4.4313541e-01]
 [3.8372386e-01 8.9681133e-05]]
